<?php
/**
 * Attribute frontend renderer
 *
 * @var $block \Smile\CustomEntityProductLink\Block\Entity\Attribute\CustomEntity\Renderer
 * @var $escaper Magento\Framework\Escaper
 */

$customEntity = $block->getCustomEntity();
?>

<a href="<?= $escaper->escapeUrl($block->getUrl($customEntity->getUrlPath())); ?>">
    <?php if ($customEntity->getImage()): ?>
    <img src="<?= $escaper->escapeUrl($customEntity->getImageUrl('image')) ?>"
         alt="<?= $customEntity->getName(); ?>"
         width="50"
         height="50" />
    <?php else: ?>
        <?= $customEntity->getName(); ?>
    <?php endif;?>
</a>
