<?php
/**
 * Attribute frontend renderer
 */
/** @var \Smile\CustomEntityProductLink\Block\Entity\Attribute\CustomEntity\Renderer $block */
$customEntity = $block->getCustomEntity();
?>

<a href="<?= $this->getUrl($customEntity->getUrlPath()); ?>">
    <?php if ($customEntity->getImage()): ?>
    <img src="<?= $customEntity->getImageUrl('image') ?>" alt="<?= $customEntity->getName(); ?>" width="50" height="50" />
    <?php else : ?>
    <?= $customEntity->getName(); ?>
    <?php endif;?>
</a>
